name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: List test files
        run: ls tests/
      - name: Check test discovery
        run: pytest --collect-only tests/
      - name: Run pytest
        run: pytest -v tests/
