name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'  # or '3.14.0-alpha.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: |
          pytest tests/
